# -*- coding: utf-8 -*-
"""Diamonds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOueJAqyQrjvxO88QKd1Q1cxREfDORWU
"""

import pandas as pd
df = pd.read_csv("diamonds.csv", index_col=0) #A primeira coluna são indices inuteis
df.head()

import pandas as pd
import matplotlib.pyplot as plt

# Carregar os dados
df = pd.read_csv("diamonds.csv", index_col=0)

# Contagem por categoria
contagem_cut = df['cut'].value_counts()

# Total de registros
total = contagem_cut.sum()

# Criar rótulos da legenda com quantidade
labels_legenda = [
    f"{cut}: {qtd}" for cut, qtd in zip(contagem_cut.index, contagem_cut.values)
]

# Criar gráfico
plt.figure(figsize=(8, 6))
plt.pie(contagem_cut, autopct='%1.1f%%')

# Título com total
plt.title(f'Distribuição dos Tipos de Corte\nTotal de dados: {total}')

# Legenda fora do gráfico
plt.legend(labels_legenda, title="Cortes", loc="center left", bbox_to_anchor=(1, 0.5))

plt.show()

df['cut'].unique() #as colunas cut, color e clarity tem strings e para trabalhar com predição
                   #precisamos transformar esses nomes em números

df['cut'].astype("category").cat.codes #esse comando transforma as palavras em números pela ordem que elas aparecem
          #como a ordem importa nesse caso, vamos definir manualmente, mas se fosse aleatório poderia ser usado

cut_class_dict = {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}
clarity_dict = {"I3": 1, "I2": 2, "I1": 3, "SI2": 4, "SI1": 5, "VS2": 6, "VS1": 7, "VVS2": 8, "VVS1": 9, "IF": 10, "FL": 11}
color_dict = {"J": 1,"I": 2,"H": 3,"G": 4,"F": 5,"E": 6,"D": 7}


df['cut'] = df['cut'].map(cut_class_dict)
df['clarity'] = df['clarity'].map(clarity_dict)
df['color'] = df['color'].map(color_dict)
df.head()

import sklearn
from sklearn import svm, preprocessing



df = sklearn.utils.shuffle(df) # Embaralhe sempre seus dados para evitar quaisquer vieses que possam surgir devido à ordem em que foram apresentados.

X = df.drop("price", axis=1).values #bloqueia a coluna preço e pega os valores das outras
                                    #uma forma de evitar trapaças é add apenas colunas de interesse

X= preprocessing.scale(X) #geralmente ajuda, mas pode fazer sem
y = df["price"].values # pega apenas os valores dos preços

import sklearn
from sklearn.linear_model import SGDRegressor


test_size = 200

X_train = X[:-test_size]
y_train = y[:-test_size]

X_test = X[-test_size:]
y_test = y[-test_size:]

clf = svm.SVR(kernel="linear")
clf.fit(X_train, y_train)

print(clf.score(X_test, y_test))

clf.score(X_test, y_test)

for X,y in zip(X_test, y_test):
    print(f"modelo: {clf.predict([X])[0]}, real: {y}")

#De forma geral o modelo está bom, porém existem alguns valores negativos que são "absurdos" por situação

clf = svm.SVR(kernel="rbf")
clf.fit(X_train, y_train)
#Rquadrado pior, porém não apresenta valores negativos

for X,y in zip(X_test, y_test):
    print(f"modelo: {clf.predict([X])[0]}, real: {y}")

#